//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 05:01:16 PM IDT 
//


package SystemEngine;

import javax.xml.bind.annotation.*;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Owner"/>
 *         &lt;element ref="{}Capacity"/>
 *         &lt;element ref="{}PPK"/>
 *         &lt;element ref="{}Route"/>
 *         &lt;element ref="{}Scheduling"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "owner",
    "capacity",
    "ppk",
    "route",
    "scheduling"
})
@XmlRootElement(name = "TransPoolTrip")
public class TransPoolTrip {

    @XmlElement(name = "Owner", required = true)
    protected String owner;
    @XmlElement(name = "Capacity")
    protected int capacity;
    @XmlElement(name = "PPK")
    protected int ppk;
    @XmlElement(name = "Route", required = true)
    protected Route route;
    @XmlElement(name = "Scheduling", required = true)
    protected Scheduling scheduling;

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     */
    public void setCapacity(int value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the ppk property.
     * 
     */
    public int getPPK() {
        return ppk;
    }

    /**
     * Sets the value of the ppk property.
     * 
     */
    public void setPPK(int value) {
        this.ppk = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link Route }
     *     
     */
    public Route getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link Route }
     *     
     */
    public void setRoute(Route value) {
        this.route = value;
    }

    /**
     * Gets the value of the scheduling property.
     * 
     * @return
     *     possible object is
     *     {@link Scheduling }
     *     
     */
    public Scheduling getScheduling() {
        return scheduling;
    }

    /**
     * Sets the value of the scheduling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scheduling }
     *     
     */
    public void setScheduling(Scheduling value) {
        this.scheduling = value;
    }

    @XmlTransient
    private RatingDriver ratingDriver;

    public int getPpk() {
        return ppk;
    }

    public void setPpk(int ppk) {
        this.ppk = ppk;
    }

    public RatingDriver getRatingDriver() {
        return ratingDriver;
    }

    public void setRatingDriver(RatingDriver ratingDriver) {
        this.ratingDriver = ratingDriver;
    }

    @XmlTransient
    private int OrderNumber;
    public int getOrderNumber() {
        return OrderNumber;
    }

    public void setOrderNumber(int orderNumber) {
        OrderNumber = orderNumber;
    }

    @XmlTransient
    private List<CapacityPerTrip> capacityPerTripList;

    public List<CapacityPerTrip> getCapacityPerTripList() {
        return capacityPerTripList;
    }

    public void setCapacityPerTripList(List<CapacityPerTrip> capacityPerTripList) {
        this.capacityPerTripList = capacityPerTripList;
    }

    public void AddToCapacityPerTripList(CapacityPerTrip capacityPerTrip)
    {
        this.capacityPerTripList.add(capacityPerTrip);
    }

    public String getDepartureStop()
    {
        String[] StopsArray = route.getPath().trim().split(",");
        return StopsArray[0];
    }

    public String getDestinationStop()
    {
        String[] StopsArray = route.getPath().trim().split(",");
        return StopsArray[StopsArray.length - 1];
    }

}
